# Generated by Django 4.2.7 on 2023-12-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_dept_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('grade', models.IntegerField(primary_key=True, serialize=False)),
                ('high_sal', models.IntegerField()),
                ('low_sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salgrade')),
            ],
        ),
    ]
