# Generated by Django 4.2.7 on 2023-12-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_salgrade_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
